version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - C:/Users/cmart/docker-postgres-data/data:/var/lib/postgresql/data
